# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from dateutil.relativedelta import relativedelta

from odoo import api, fields, models, _
from odoo.exceptions import UserError
from odoo.tools import float_compare


class Part(models.Model):
    _inherit = 'part.order'

    purchase_order_count = fields.Integer("Number of Purchase Order", compute='_compute_purchase_order_count', groups='purchase.group_purchase_user')

class PartLine(models.Model):
    _inherit = 'part.line'

    purchase_line_ids = fields.One2many('purchase.order.line', 'part_line_id', string="Generated Purchase Lines", readonly=True, help="Purchase line generated by this Part item on order confirmation, or when the quantity was increased.")
    purchase_line_count = fields.Integer("Number of generated purchase items", compute='_compute_purchase_count', compute_sudo=True)
